library(gdata) # read.xls()
library(ggplot2)
library(reshape2)  # melt()
library(scales)  # pretty_breaks()
library(plyr)  # revalue()
library(tidyr)  # spread()
library(RColorBrewer)
library(gridExtra)  # grid.arrange()
library(printr)
library(deamer)  # deamerKE()
library(tidyr)
library(mclust)  # mclust()
library(dplyr)  # select()
library(pander)
library(grid)  # unit.pmax
library(gtable)  # rbind.gtable()
library(knitr)  # kable()
library(cowplot)
